//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MensajeInicioSesion", Namespace="http://schemas.datacontract.org/2004/07/ServiciosSistemaTutorias")]
    public partial class MensajeInicioSesion : object
    {
        
        private bool errorField;
        
        private string mensajeField;
        
        private ServiceReference1.Academicos usuarioAcademicoField;
        
        private ServiceReference1.RolesAcademicos usuarioRolAcademicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Academicos usuarioAcademico
        {
            get
            {
                return this.usuarioAcademicoField;
            }
            set
            {
                this.usuarioAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RolesAcademicos usuarioRolAcademico
        {
            get
            {
                return this.usuarioRolAcademicoField;
            }
            set
            {
                this.usuarioRolAcademicoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Academicos", Namespace="http://schemas.datacontract.org/2004/07/ServiciosSistemaTutorias.Modelo")]
    public partial class Academicos : object
    {
        
        private string ApellidoMaternoField;
        
        private string ApellidoPaternoField;
        
        private string CorreoField;
        
        private ServiceReference1.ExperienciasEducativas[] ExperienciasEducativasField;
        
        private string NombresField;
        
        private string NumPersonalField;
        
        private ServiceReference1.RolesAcademicos[] RolesAcademicosField;
        
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno
        {
            get
            {
                return this.ApellidoMaternoField;
            }
            set
            {
                this.ApellidoMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno
        {
            get
            {
                return this.ApellidoPaternoField;
            }
            set
            {
                this.ApellidoPaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ExperienciasEducativas[] ExperienciasEducativas
        {
            get
            {
                return this.ExperienciasEducativasField;
            }
            set
            {
                this.ExperienciasEducativasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumPersonal
        {
            get
            {
                return this.NumPersonalField;
            }
            set
            {
                this.NumPersonalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RolesAcademicos[] RolesAcademicos
        {
            get
            {
                return this.RolesAcademicosField;
            }
            set
            {
                this.RolesAcademicosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RolesAcademicos", Namespace="http://schemas.datacontract.org/2004/07/ServiciosSistemaTutorias.Modelo")]
    public partial class RolesAcademicos : object
    {
        
        private ServiceReference1.Academicos AcademicosField;
        
        private System.Nullable<int> IDRolField;
        
        private int IDRolAcademicoField;
        
        private string NumPersonalField;
        
        private string PasswordField;
        
        private ServiceReference1.ReportesGenerales[] ReportesGeneralesField;
        
        private ServiceReference1.Roles RolesField;
        
        private ServiceReference1.TutoriasAcademicas[] TutoriasAcademicasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Academicos Academicos
        {
            get
            {
                return this.AcademicosField;
            }
            set
            {
                this.AcademicosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDRol
        {
            get
            {
                return this.IDRolField;
            }
            set
            {
                this.IDRolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDRolAcademico
        {
            get
            {
                return this.IDRolAcademicoField;
            }
            set
            {
                this.IDRolAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumPersonal
        {
            get
            {
                return this.NumPersonalField;
            }
            set
            {
                this.NumPersonalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ReportesGenerales[] ReportesGenerales
        {
            get
            {
                return this.ReportesGeneralesField;
            }
            set
            {
                this.ReportesGeneralesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Roles Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TutoriasAcademicas[] TutoriasAcademicas
        {
            get
            {
                return this.TutoriasAcademicasField;
            }
            set
            {
                this.TutoriasAcademicasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExperienciasEducativas", Namespace="http://schemas.datacontract.org/2004/07/ServiciosSistemaTutorias.Modelo")]
    public partial class ExperienciasEducativas : object
    {
        
        private ServiceReference1.Academicos AcademicosField;
        
        private System.Nullable<int> CreditosField;
        
        private ServiceReference1.ExperienciasEducativasEstudiantes[] ExperienciasEducativasEstudiantesField;
        
        private int NRCField;
        
        private string NombreField;
        
        private string NumPersonalField;
        
        private ServiceReference1.ProblematicasAcademicas[] ProblematicasAcademicasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Academicos Academicos
        {
            get
            {
                return this.AcademicosField;
            }
            set
            {
                this.AcademicosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Creditos
        {
            get
            {
                return this.CreditosField;
            }
            set
            {
                this.CreditosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ExperienciasEducativasEstudiantes[] ExperienciasEducativasEstudiantes
        {
            get
            {
                return this.ExperienciasEducativasEstudiantesField;
            }
            set
            {
                this.ExperienciasEducativasEstudiantesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NRC
        {
            get
            {
                return this.NRCField;
            }
            set
            {
                this.NRCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumPersonal
        {
            get
            {
                return this.NumPersonalField;
            }
            set
            {
                this.NumPersonalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProblematicasAcademicas[] ProblematicasAcademicas
        {
            get
            {
                return this.ProblematicasAcademicasField;
            }
            set
            {
                this.ProblematicasAcademicasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExperienciasEducativasEstudiantes", Namespace="http://schemas.datacontract.org/2004/07/ServiciosSistemaTutorias.Modelo")]
    public partial class ExperienciasEducativasEstudiantes : object
    {
        
        private ServiceReference1.Estudiantes EstudiantesField;
        
        private ServiceReference1.ExperienciasEducativas ExperienciasEducativasField;
        
        private int IDExperienciaEducativaEstudianteField;
        
        private string MatriculaField;
        
        private System.Nullable<int> NRCField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Estudiantes Estudiantes
        {
            get
            {
                return this.EstudiantesField;
            }
            set
            {
                this.EstudiantesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ExperienciasEducativas ExperienciasEducativas
        {
            get
            {
                return this.ExperienciasEducativasField;
            }
            set
            {
                this.ExperienciasEducativasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDExperienciaEducativaEstudiante
        {
            get
            {
                return this.IDExperienciaEducativaEstudianteField;
            }
            set
            {
                this.IDExperienciaEducativaEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matricula
        {
            get
            {
                return this.MatriculaField;
            }
            set
            {
                this.MatriculaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NRC
        {
            get
            {
                return this.NRCField;
            }
            set
            {
                this.NRCField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProblematicasAcademicas", Namespace="http://schemas.datacontract.org/2004/07/ServiciosSistemaTutorias.Modelo")]
    public partial class ProblematicasAcademicas : object
    {
        
        private ServiceReference1.CategoriasProblematica CategoriasProblematicaField;
        
        private string DescripcionField;
        
        private string EstadoField;
        
        private ServiceReference1.ExperienciasEducativas ExperienciasEducativasField;
        
        private System.Nullable<int> IDCategoriaField;
        
        private int IDProblematicaAcademicaField;
        
        private System.Nullable<int> IDTutoriaAcademicaEstudianteField;
        
        private System.Nullable<int> NRCField;
        
        private string SolucionField;
        
        private ServiceReference1.TutoriasAcademicasEstudiantes TutoriasAcademicasEstudiantesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.CategoriasProblematica CategoriasProblematica
        {
            get
            {
                return this.CategoriasProblematicaField;
            }
            set
            {
                this.CategoriasProblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ExperienciasEducativas ExperienciasEducativas
        {
            get
            {
                return this.ExperienciasEducativasField;
            }
            set
            {
                this.ExperienciasEducativasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDCategoria
        {
            get
            {
                return this.IDCategoriaField;
            }
            set
            {
                this.IDCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDProblematicaAcademica
        {
            get
            {
                return this.IDProblematicaAcademicaField;
            }
            set
            {
                this.IDProblematicaAcademicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDTutoriaAcademicaEstudiante
        {
            get
            {
                return this.IDTutoriaAcademicaEstudianteField;
            }
            set
            {
                this.IDTutoriaAcademicaEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NRC
        {
            get
            {
                return this.NRCField;
            }
            set
            {
                this.NRCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Solucion
        {
            get
            {
                return this.SolucionField;
            }
            set
            {
                this.SolucionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TutoriasAcademicasEstudiantes TutoriasAcademicasEstudiantes
        {
            get
            {
                return this.TutoriasAcademicasEstudiantesField;
            }
            set
            {
                this.TutoriasAcademicasEstudiantesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estudiantes", Namespace="http://schemas.datacontract.org/2004/07/ServiciosSistemaTutorias.Modelo")]
    public partial class Estudiantes : object
    {
        
        private string ApellidoMaternoField;
        
        private string ApellidoPaternoField;
        
        private string CorreoField;
        
        private ServiceReference1.ExperienciasEducativasEstudiantes[] ExperienciasEducativasEstudiantesField;
        
        private System.Nullable<int> IDProgramaEducativoField;
        
        private string MatriculaField;
        
        private string NombresField;
        
        private ServiceReference1.ProgramasEducativos ProgramasEducativosField;
        
        private string TelefonoField;
        
        private ServiceReference1.TutoriasAcademicasEstudiantes[] TutoriasAcademicasEstudiantesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno
        {
            get
            {
                return this.ApellidoMaternoField;
            }
            set
            {
                this.ApellidoMaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno
        {
            get
            {
                return this.ApellidoPaternoField;
            }
            set
            {
                this.ApellidoPaternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ExperienciasEducativasEstudiantes[] ExperienciasEducativasEstudiantes
        {
            get
            {
                return this.ExperienciasEducativasEstudiantesField;
            }
            set
            {
                this.ExperienciasEducativasEstudiantesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDProgramaEducativo
        {
            get
            {
                return this.IDProgramaEducativoField;
            }
            set
            {
                this.IDProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matricula
        {
            get
            {
                return this.MatriculaField;
            }
            set
            {
                this.MatriculaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProgramasEducativos ProgramasEducativos
        {
            get
            {
                return this.ProgramasEducativosField;
            }
            set
            {
                this.ProgramasEducativosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TutoriasAcademicasEstudiantes[] TutoriasAcademicasEstudiantes
        {
            get
            {
                return this.TutoriasAcademicasEstudiantesField;
            }
            set
            {
                this.TutoriasAcademicasEstudiantesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProgramasEducativos", Namespace="http://schemas.datacontract.org/2004/07/ServiciosSistemaTutorias.Modelo")]
    public partial class ProgramasEducativos : object
    {
        
        private ServiceReference1.AreasAcademicas AreasAcademicasField;
        
        private ServiceReference1.Estudiantes[] EstudiantesField;
        
        private System.Nullable<int> IDAreaAcademicaField;
        
        private int IDProgramaEducativoField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.AreasAcademicas AreasAcademicas
        {
            get
            {
                return this.AreasAcademicasField;
            }
            set
            {
                this.AreasAcademicasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Estudiantes[] Estudiantes
        {
            get
            {
                return this.EstudiantesField;
            }
            set
            {
                this.EstudiantesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDAreaAcademica
        {
            get
            {
                return this.IDAreaAcademicaField;
            }
            set
            {
                this.IDAreaAcademicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDProgramaEducativo
        {
            get
            {
                return this.IDProgramaEducativoField;
            }
            set
            {
                this.IDProgramaEducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TutoriasAcademicasEstudiantes", Namespace="http://schemas.datacontract.org/2004/07/ServiciosSistemaTutorias.Modelo")]
    public partial class TutoriasAcademicasEstudiantes : object
    {
        
        private ServiceReference1.Estudiantes EstudiantesField;
        
        private System.Nullable<int> IDTutoriaAcademicaField;
        
        private int IDTutoriaAcademicaestudianteField;
        
        private string MatriculaField;
        
        private ServiceReference1.ProblematicasAcademicas[] ProblematicasAcademicasField;
        
        private ServiceReference1.TutoriasAcademicas TutoriasAcademicasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.Estudiantes Estudiantes
        {
            get
            {
                return this.EstudiantesField;
            }
            set
            {
                this.EstudiantesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDTutoriaAcademica
        {
            get
            {
                return this.IDTutoriaAcademicaField;
            }
            set
            {
                this.IDTutoriaAcademicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDTutoriaAcademicaestudiante
        {
            get
            {
                return this.IDTutoriaAcademicaestudianteField;
            }
            set
            {
                this.IDTutoriaAcademicaestudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Matricula
        {
            get
            {
                return this.MatriculaField;
            }
            set
            {
                this.MatriculaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProblematicasAcademicas[] ProblematicasAcademicas
        {
            get
            {
                return this.ProblematicasAcademicasField;
            }
            set
            {
                this.ProblematicasAcademicasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TutoriasAcademicas TutoriasAcademicas
        {
            get
            {
                return this.TutoriasAcademicasField;
            }
            set
            {
                this.TutoriasAcademicasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AreasAcademicas", Namespace="http://schemas.datacontract.org/2004/07/ServiciosSistemaTutorias.Modelo")]
    public partial class AreasAcademicas : object
    {
        
        private int IDAreaAcademicaField;
        
        private string NombreField;
        
        private ServiceReference1.ProgramasEducativos[] ProgramasEducativosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDAreaAcademica
        {
            get
            {
                return this.IDAreaAcademicaField;
            }
            set
            {
                this.IDAreaAcademicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProgramasEducativos[] ProgramasEducativos
        {
            get
            {
                return this.ProgramasEducativosField;
            }
            set
            {
                this.ProgramasEducativosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TutoriasAcademicas", Namespace="http://schemas.datacontract.org/2004/07/ServiciosSistemaTutorias.Modelo")]
    public partial class TutoriasAcademicas : object
    {
        
        private System.Nullable<System.TimeSpan> DuracionField;
        
        private System.Nullable<System.DateTime> FechaField;
        
        private System.Nullable<System.DateTime> FechaCierreField;
        
        private System.Nullable<int> IDPeriodoEscolarField;
        
        private System.Nullable<int> IDReporteTutoriaField;
        
        private System.Nullable<int> IDRolAcademicoField;
        
        private int IDTutoriaAcademicaField;
        
        private System.Nullable<int> NumSesionField;
        
        private ServiceReference1.PeriodosEscolares PeriodosEscolaresField;
        
        private ServiceReference1.ReportesTutoria[] ReportesTutoriaField;
        
        private ServiceReference1.ReportesTutoria ReportesTutoria1Field;
        
        private ServiceReference1.RolesAcademicos RolesAcademicosField;
        
        private ServiceReference1.TutoriasAcademicasEstudiantes[] TutoriasAcademicasEstudiantesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> Duracion
        {
            get
            {
                return this.DuracionField;
            }
            set
            {
                this.DuracionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaCierre
        {
            get
            {
                return this.FechaCierreField;
            }
            set
            {
                this.FechaCierreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDPeriodoEscolar
        {
            get
            {
                return this.IDPeriodoEscolarField;
            }
            set
            {
                this.IDPeriodoEscolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDReporteTutoria
        {
            get
            {
                return this.IDReporteTutoriaField;
            }
            set
            {
                this.IDReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDRolAcademico
        {
            get
            {
                return this.IDRolAcademicoField;
            }
            set
            {
                this.IDRolAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDTutoriaAcademica
        {
            get
            {
                return this.IDTutoriaAcademicaField;
            }
            set
            {
                this.IDTutoriaAcademicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumSesion
        {
            get
            {
                return this.NumSesionField;
            }
            set
            {
                this.NumSesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.PeriodosEscolares PeriodosEscolares
        {
            get
            {
                return this.PeriodosEscolaresField;
            }
            set
            {
                this.PeriodosEscolaresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ReportesTutoria[] ReportesTutoria
        {
            get
            {
                return this.ReportesTutoriaField;
            }
            set
            {
                this.ReportesTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ReportesTutoria ReportesTutoria1
        {
            get
            {
                return this.ReportesTutoria1Field;
            }
            set
            {
                this.ReportesTutoria1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RolesAcademicos RolesAcademicos
        {
            get
            {
                return this.RolesAcademicosField;
            }
            set
            {
                this.RolesAcademicosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TutoriasAcademicasEstudiantes[] TutoriasAcademicasEstudiantes
        {
            get
            {
                return this.TutoriasAcademicasEstudiantesField;
            }
            set
            {
                this.TutoriasAcademicasEstudiantesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriasProblematica", Namespace="http://schemas.datacontract.org/2004/07/ServiciosSistemaTutorias.Modelo")]
    public partial class CategoriasProblematica : object
    {
        
        private int IDCategoriaField;
        
        private ServiceReference1.ProblematicasAcademicas[] ProblematicasAcademicasField;
        
        private string TipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDCategoria
        {
            get
            {
                return this.IDCategoriaField;
            }
            set
            {
                this.IDCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ProblematicasAcademicas[] ProblematicasAcademicas
        {
            get
            {
                return this.ProblematicasAcademicasField;
            }
            set
            {
                this.ProblematicasAcademicasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodosEscolares", Namespace="http://schemas.datacontract.org/2004/07/ServiciosSistemaTutorias.Modelo")]
    public partial class PeriodosEscolares : object
    {
        
        private System.Nullable<System.DateTime> FechaFinField;
        
        private System.Nullable<System.DateTime> FechaInicioField;
        
        private int IDPeriodoEscolarField;
        
        private ServiceReference1.TutoriasAcademicas[] TutoriasAcademicasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaFin
        {
            get
            {
                return this.FechaFinField;
            }
            set
            {
                this.FechaFinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaInicio
        {
            get
            {
                return this.FechaInicioField;
            }
            set
            {
                this.FechaInicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPeriodoEscolar
        {
            get
            {
                return this.IDPeriodoEscolarField;
            }
            set
            {
                this.IDPeriodoEscolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TutoriasAcademicas[] TutoriasAcademicas
        {
            get
            {
                return this.TutoriasAcademicasField;
            }
            set
            {
                this.TutoriasAcademicasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportesTutoria", Namespace="http://schemas.datacontract.org/2004/07/ServiciosSistemaTutorias.Modelo")]
    public partial class ReportesTutoria : object
    {
        
        private string ComentarioGeneralField;
        
        private string DescripcionField;
        
        private int IDReporteTutoriaField;
        
        private System.Nullable<int> IDTutoriaAcademicaField;
        
        private ServiceReference1.TutoriasAcademicas TutoriasAcademicasField;
        
        private ServiceReference1.TutoriasAcademicas[] TutoriasAcademicas1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComentarioGeneral
        {
            get
            {
                return this.ComentarioGeneralField;
            }
            set
            {
                this.ComentarioGeneralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDReporteTutoria
        {
            get
            {
                return this.IDReporteTutoriaField;
            }
            set
            {
                this.IDReporteTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDTutoriaAcademica
        {
            get
            {
                return this.IDTutoriaAcademicaField;
            }
            set
            {
                this.IDTutoriaAcademicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TutoriasAcademicas TutoriasAcademicas
        {
            get
            {
                return this.TutoriasAcademicasField;
            }
            set
            {
                this.TutoriasAcademicasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TutoriasAcademicas[] TutoriasAcademicas1
        {
            get
            {
                return this.TutoriasAcademicas1Field;
            }
            set
            {
                this.TutoriasAcademicas1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Roles", Namespace="http://schemas.datacontract.org/2004/07/ServiciosSistemaTutorias.Modelo")]
    public partial class Roles : object
    {
        
        private int IDRolField;
        
        private string NombreRolField;
        
        private ServiceReference1.RolesAcademicos[] RolesAcademicosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDRol
        {
            get
            {
                return this.IDRolField;
            }
            set
            {
                this.IDRolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreRol
        {
            get
            {
                return this.NombreRolField;
            }
            set
            {
                this.NombreRolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RolesAcademicos[] RolesAcademicos
        {
            get
            {
                return this.RolesAcademicosField;
            }
            set
            {
                this.RolesAcademicosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportesGenerales", Namespace="http://schemas.datacontract.org/2004/07/ServiciosSistemaTutorias.Modelo")]
    public partial class ReportesGenerales : object
    {
        
        private string ComentarioGeneralField;
        
        private string DescripcionField;
        
        private int IDReporteGeneralField;
        
        private System.Nullable<int> IDRolAcademicoField;
        
        private ServiceReference1.RolesAcademicos RolesAcademicosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComentarioGeneral
        {
            get
            {
                return this.ComentarioGeneralField;
            }
            set
            {
                this.ComentarioGeneralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDReporteGeneral
        {
            get
            {
                return this.IDReporteGeneralField;
            }
            set
            {
                this.IDReporteGeneralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDRolAcademico
        {
            get
            {
                return this.IDRolAcademicoField;
            }
            set
            {
                this.IDRolAcademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.RolesAcademicos RolesAcademicos
        {
            get
            {
                return this.RolesAcademicosField;
            }
            set
            {
                this.RolesAcademicosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TutoriaPeriodo", Namespace="http://schemas.datacontract.org/2004/07/ServiciosSistemaTutorias")]
    public partial class TutoriaPeriodo : object
    {
        
        private ServiceReference1.PeriodosEscolares periodoEscolarField;
        
        private ServiceReference1.TutoriasAcademicas tutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.PeriodosEscolares periodoEscolar
        {
            get
            {
                return this.periodoEscolarField;
            }
            set
            {
                this.periodoEscolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.TutoriasAcademicas tutoria
        {
            get
            {
                return this.tutoriaField;
            }
            set
            {
                this.tutoriaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/iniciarSesion", ReplyAction="http://tempuri.org/IService1/iniciarSesionResponse")]
        System.Threading.Tasks.Task<ServiceReference1.MensajeInicioSesion> iniciarSesionAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerTutoriasAcademicas", ReplyAction="http://tempuri.org/IService1/obtenerTutoriasAcademicasResponse")]
        System.Threading.Tasks.Task<ServiceReference1.TutoriaPeriodo[]> obtenerTutoriasAcademicasAsync(int IDRolAcademico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerPeriodosEscolares", ReplyAction="http://tempuri.org/IService1/obtenerPeriodosEscolaresResponse")]
        System.Threading.Tasks.Task<ServiceReference1.PeriodosEscolares[]> obtenerPeriodosEscolaresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarTutoriaAcademica", ReplyAction="http://tempuri.org/IService1/registrarTutoriaAcademicaResponse")]
        System.Threading.Tasks.Task<bool> registrarTutoriaAcademicaAsync(System.DateTime FechaTutoria, int NumSesionTutoria, int IDPeriodoEscolarTutoria, int IDRolAcademicoTutoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarReporteTutoria", ReplyAction="http://tempuri.org/IService1/registrarReporteTutoriaResponse")]
        System.Threading.Tasks.Task<bool> registrarReporteTutoriaAsync(string descripcion, string comentariosGenerales, int IDTutoriaAcademica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarTutoriaAcademica", ReplyAction="http://tempuri.org/IService1/consultarTutoriaAcademicaResponse")]
        System.Threading.Tasks.Task<ServiceReference1.TutoriaPeriodo> consultarTutoriaAcademicaAsync(int IDTutoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modificarTutoriaAcademica", ReplyAction="http://tempuri.org/IService1/modificarTutoriaAcademicaResponse")]
        System.Threading.Tasks.Task<bool> modificarTutoriaAcademicaAsync(int IDTutoria, System.DateTime FechaTutoria, int NumSesionTutoria, int IDPeriodoEscolarTutoria, int IDRolAcademicoTutoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarEstudiante", ReplyAction="http://tempuri.org/IService1/registrarEstudianteResponse")]
        System.Threading.Tasks.Task<bool> registrarEstudianteAsync(string matricula, string nombre, string apellidoPaterno, string apellidoMaterno, string correo, string telefono, int idProgramaEducativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/obtenerProgramaEducativos", ReplyAction="http://tempuri.org/IService1/obtenerProgramaEducativosResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ProgramasEducativos[]> obtenerProgramaEducativosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IService1Channel : ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference1.IService1>, ServiceReference1.IService1
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MensajeInicioSesion> iniciarSesionAsync(string username, string password)
        {
            return base.Channel.iniciarSesionAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TutoriaPeriodo[]> obtenerTutoriasAcademicasAsync(int IDRolAcademico)
        {
            return base.Channel.obtenerTutoriasAcademicasAsync(IDRolAcademico);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.PeriodosEscolares[]> obtenerPeriodosEscolaresAsync()
        {
            return base.Channel.obtenerPeriodosEscolaresAsync();
        }
        
        public System.Threading.Tasks.Task<bool> registrarTutoriaAcademicaAsync(System.DateTime FechaTutoria, int NumSesionTutoria, int IDPeriodoEscolarTutoria, int IDRolAcademicoTutoria)
        {
            return base.Channel.registrarTutoriaAcademicaAsync(FechaTutoria, NumSesionTutoria, IDPeriodoEscolarTutoria, IDRolAcademicoTutoria);
        }
        
        public System.Threading.Tasks.Task<bool> registrarReporteTutoriaAsync(string descripcion, string comentariosGenerales, int IDTutoriaAcademica)
        {
            return base.Channel.registrarReporteTutoriaAsync(descripcion, comentariosGenerales, IDTutoriaAcademica);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TutoriaPeriodo> consultarTutoriaAcademicaAsync(int IDTutoria)
        {
            return base.Channel.consultarTutoriaAcademicaAsync(IDTutoria);
        }
        
        public System.Threading.Tasks.Task<bool> modificarTutoriaAcademicaAsync(int IDTutoria, System.DateTime FechaTutoria, int NumSesionTutoria, int IDPeriodoEscolarTutoria, int IDRolAcademicoTutoria)
        {
            return base.Channel.modificarTutoriaAcademicaAsync(IDTutoria, FechaTutoria, NumSesionTutoria, IDPeriodoEscolarTutoria, IDRolAcademicoTutoria);
        }
        
        public System.Threading.Tasks.Task<bool> registrarEstudianteAsync(string matricula, string nombre, string apellidoPaterno, string apellidoMaterno, string correo, string telefono, int idProgramaEducativo)
        {
            return base.Channel.registrarEstudianteAsync(matricula, nombre, apellidoPaterno, apellidoMaterno, correo, telefono, idProgramaEducativo);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ProgramasEducativos[]> obtenerProgramaEducativosAsync()
        {
            return base.Channel.obtenerProgramaEducativosAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:62370/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
